# Generated by Django 3.2.4 on 2021-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='date_create',
            new_name='created_at',
        ),
    ]
